### ISSUE TITLE
Discussion: Explicit upvotes

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#29]
Right now we only use clicks and impressions as an indicator for interest. User in this thread:

https://github.com/GetStream/Winds/issues/11

Suggested adding direct up and down votes.

**Comment by Wowl** [comment]
That'd be awesome, so the reader optimizes for good articles instead of clickbait headlines.

**Comment by mlapierre** [comment]
As @mathias and @hyperfekt mentioned, it would be a good indicator of interest. 

Clicks and impressions really seem like indicators of _potential_ interest - articles show up in our feed because they're like other things we're interested in, at least in general. I.e., that doesn't necessarily mean any specific article is interesting. The same goes for clicks - we click because the title/summary seems like it might be interesting. But it might turn out that the article wasn't interesting at all (e.g., clickbait).

So explicit upvotes would be good input for the learning algorithms. It could also be a useful comparison with other measures of similarity (e.g., clustering based on impressions and clicks might suggest certain groupings that turn out to be at odds with clustering based on the content of upvoted articles. Or maybe upvotes turn out to be a more precise indicator and impressions turn out to be relatively uninformative...)

I have a side-project doing something very similar to this. I currently use Inoreader as my rss reader, and I send any articles that I really like to Evernote (to capture the 'like' and to archive the content). Those liked articles (among the full set of feeds) provide all the info I need to predict other articles I'll like. But I don't currently have a good way to compare my interests with other people's, so I'm really interested in this project (with or without explicit upvotes).

**Comment by mlapierre** [comment]
I see there's now a heart icon to "like" articles. 

Except it's applied to all articles in a feed, rather than to individual articles. Was that intentional?
