### ISSUE TITLE
error on import of initial data

### ISSUE THREAD

**Issue by the4ndy** [GetStream/Winds#92]
I have run the command to import the initial data during an first time install on a fresh ubuntu 16.04 machine and I get this error/output

```
thesheriff@rss:~/Winds$ sudo node load_initial_data.js 
/home/thesheriff/Winds/load_initial_data.js:74
    let topicNames = Object.keys(initialData)
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

it doesnt matter if i run with or without sudo, same error
any ideas?

**Comment by dwightgunning** [comment]
Not that Winds was initially developed with Node v7 so that's ideally what you should be running. You can check by running `$ node -v`

I also spotted that Ubuntu 16.04 ships with v4.2.6 and when I downgrade to that version I get the same error.

Assuming you just need to upgrade Node, try this guide for Ubuntu 16.04: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04

Also, in generally you __should not__ need `sudo` while developing or running Winds (other node projects).

**Comment by nparsons08** [comment]
👍 on @dwightgunning's answer. @the4ndy, please upgrade your Node.js version or attempt to run with the --harmony flag.
